
include theos/makefiles/common.mk

TOOL_NAME = SpireInstaller
SpireInstaller_FILES = Installer.m partial.c
SpireInstaller_FRAMEWORKS = Foundation CoreFoundation
SpireInstaller_LDFLAGS = -lcurl -lz

include $(THEOS_MAKE_PATH)/tool.mk

